version: "3.9"

services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      DATABASE_HOSTNAME: localhost
      DATABASE_PORT: "5432"
      DATABASE_NAME: fastapi
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: password123
      SECRET_KEY: supersecretkey
      ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRE_MINUTES: "30"
